# Generated by Django 5.2.16 on 2026-08-06 17:34

import core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-created_at', '-pk'], 'verbose_name': 'новостная статья', 'verbose_name_plural': 'новостные статьи'},
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news_articles', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=models.TextField(verbose_name='полный текст'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, upload_to='news/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp']), core.validators.validate_image_size], verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='in_game_date',
            field=models.DateField(blank=True, null=True, verbose_name='игровая дата'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='news_type',
            field=models.CharField(choices=[('world', 'Мировые новости'), ('knox', 'Новости зоны Нокс'), ('military', 'Военная сводка'), ('scientific', 'Научный отчёт'), ('radio', 'Радиосообщение'), ('rumor', 'Слух выживших')], default='knox', max_length=20, verbose_name='тип новости'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='summary',
            field=models.CharField(max_length=400, verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(max_length=200, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата изменения'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='visibility',
            field=models.CharField(choices=[('survivors', 'Выжившие и администраторы'), ('admin_only', 'Только администраторы')], default='survivors', max_length=20, verbose_name='видимость'),
        ),
    ]
