# Generated by Django 5.2.16 on 2026-08-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(default='Knox Community Network', max_length=100)),
                ('welcome_message', models.TextField(default='A volunteer relay for survivors inside the Knox Exclusion Zone.')),
                ('emergency_message', models.CharField(default='Conserve water. Keep radios tuned to 88.7 FM.', max_length=255)),
                ('server_status', models.CharField(default='ONLINE - Signal unstable', max_length=80)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
