# Generated by Django 5.2.16 on 2026-08-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'настройки сайта', 'verbose_name_plural': 'настройки сайта'},
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='emergency_message',
            field=models.CharField(default='Берегите воду. Держите радиоприёмники на частоте 88,7 МГц.', max_length=255, verbose_name='экстренное сообщение'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='последнее обновление'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='server_status',
            field=models.CharField(default='В СЕТИ — сигнал нестабилен', max_length=80, verbose_name='состояние сервера'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='website_name',
            field=models.CharField(default='Общественная сеть Нокса', max_length=100, verbose_name='название сайта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='welcome_message',
            field=models.TextField(default='Добровольный узел связи для выживших внутри закрытой зоны Нокс.', verbose_name='приветствие'),
        ),
    ]
