# Generated by Django 5.2.16 on 2026-08-06 17:12

import core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('for_sale', 'For Sale'), ('wanted', 'Wanted'), ('trade', 'Trade'), ('services', 'Services'), ('group_recruitment', 'Group Recruitment'), ('warning', 'Warning'), ('other', 'Other')], max_length=24)),
                ('character_name', models.CharField(max_length=100)),
                ('price_or_trade', models.CharField(max_length=200)),
                ('meeting_location', models.CharField(max_length=200)),
                ('contact_information', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='marketplace/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp']), core.validators.validate_image_size])),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('closed', 'Closed')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
