# Generated by Django 5.2.16 on 2026-08-06 17:34

import core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketplacelisting',
            options={'ordering': ['-created_at'], 'verbose_name': 'объявление', 'verbose_name_plural': 'объявления'},
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listings', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='category',
            field=models.CharField(choices=[('for_sale', 'Продажа'), ('wanted', 'Розыск'), ('trade', 'Обмен'), ('services', 'Услуги'), ('group_recruitment', 'Набор в группу'), ('warning', 'Предупреждение'), ('other', 'Прочее')], max_length=24, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='character_name',
            field=models.CharField(max_length=100, verbose_name='имя персонажа'),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='contact_information',
            field=models.CharField(max_length=200, verbose_name='способ связи'),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='image',
            field=models.ImageField(blank=True, help_text='Необязательное изображение размером не более 3 МБ.', upload_to='marketplace/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp']), core.validators.validate_image_size], verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='meeting_location',
            field=models.CharField(max_length=200, verbose_name='место встречи'),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='price_or_trade',
            field=models.CharField(max_length=200, verbose_name='цена или условия обмена'),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('sold', 'Продано'), ('closed', 'Закрыто')], default='active', max_length=10, verbose_name='состояние'),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='title',
            field=models.CharField(max_length=200, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата изменения'),
        ),
    ]
