# Generated by Django 5.2.16 on 2026-08-06 17:12

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(blank=True, max_length=100)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', validators=[core.validators.validate_image_size])),
                ('biography', models.TextField(blank=True)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('alive', 'Alive'), ('missing', 'Missing'), ('injured', 'Injured'), ('unknown', 'Unknown'), ('dead', 'Dead')], default='unknown', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
