# Generated by Django 5.2.16 on 2026-08-06 17:34

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'профиль выжившего', 'verbose_name_plural': 'профили выживших'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', validators=[core.validators.validate_image_size], verbose_name='аватар'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='biography',
            field=models.TextField(blank=True, verbose_name='краткая биография'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='character_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='имя персонажа'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, verbose_name='занятие'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('alive', 'Жив'), ('missing', 'Пропал без вести'), ('injured', 'Ранен'), ('unknown', 'Неизвестно'), ('dead', 'Мёртв')], default='unknown', max_length=10, verbose_name='текущее состояние'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
